// src/models.rs
// This file will contain the data structures for the ledger, such as Transaction and Balance.

use serde::{Serialize, Deserialize};
use chrono::{NaiveDate, Local};

/// Represents a single financial transaction in the ledger.
///
/// # Fields
/// * `id` - A unique identifier for the transaction. This is typically generated by the database.
/// * `date` - The date when the transaction occurred, in YYYY-MM-DD format.
/// * `person` - The name of the person involved in the transaction.
/// * `amount` - The amount of the transaction, in cents. Positive if the person owes the user,
///              negative if the user owes the person.
/// * `note` - An optional descriptive note for the transaction.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct Transaction {
    pub id: Option<i64>,
    pub date: String,
    pub person: String,
    pub amount: i64,
    pub note: Option<String>,
}

impl Transaction {
    /// Creates a new `Transaction` instance.
    ///
    /// # Arguments
    /// * `date` - The date of the transaction (YYYY-MM-DD).
    /// * `person` - The person involved.
    /// * `amount` - The transaction amount in cents.
    /// * ``note` - An optional note.
    ///
    /// # Returns
    /// A `Result` containing the `Transaction` on success, or a `String` error message on validation failure.
    pub fn new(date: String, person: String, amount: i64, note: Option<String>) -> Result<Self, String> {
        // Validate person field
        if person.trim().is_empty() {
            return Err("Person name cannot be empty.".to_string());
        }

        // Validate date format (YYYY-MM-DD)
        if NaiveDate::parse_from_str(&date, "%Y-%m-%d").is_err() {
            return Err("Date must be in YYYY-MM-DD format.".to_string());
        }

        Ok(Transaction {
            id: None, // ID is typically assigned by the database upon insertion
            date,
            person,
            amount,
            note,
        })
    }

    /// Creates a new `Transaction` with the current date if not provided.
    /// This is a convenience constructor for CLI/FFI where date might be optional.
    pub fn new_with_defaults(date: Option<String>, person: String, amount: i64, note: Option<String>) -> Result<Self, String> {
        let final_date = match date {
            Some(d) => d,
            None => Local::now().format("%Y-%m-%d").to_string(),
        };
        Self::new(final_date, person, amount, note)
    }
}

/// Represents the aggregated balance for a specific person.
/// This is a derived entity, computed from `Transaction` records.
///
/// # Fields
/// * `person` - The name of the person for whom the balance is calculated.
/// * `total_amount` - The net balance for the person, in cents.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct Balance {
    pub person: String,
    pub total_amount: i64,
}

#[cfg(test)]
mod tests {
    use super::{Transaction, Balance};
    use chrono::Local;

    #[test]
    fn test_transaction_new_valid() {
        let transaction = Transaction::new(
            "2025-01-15".to_string(),
            "Alice".to_string(),
            1000,
            Some("Lunch".to_string()),
        );
        assert!(transaction.is_ok());
        let tx = transaction.unwrap();
        assert_eq!(tx.date, "2025-01-15");
        assert_eq!(tx.person, "Alice");
        assert_eq!(tx.amount, 1000);
        assert_eq!(tx.note, Some("Lunch".to_string()));
        assert_eq!(tx.id, None);
    }

    #[test]
    fn test_transaction_new_empty_person() {
        let transaction = Transaction::new(
            "2025-01-15".to_string(),
            "".to_string(),
            500,
            None,
        );
        assert!(transaction.is_err());
        assert_eq!(transaction.unwrap_err(), "Person name cannot be empty.");

        let transaction_whitespace = Transaction::new(
            "2025-01-15".to_string(),
            "   ".to_string(),
            500,
            None,
        );
        assert!(transaction_whitespace.is_err());
        assert_eq!(transaction_whitespace.unwrap_err(), "Person name cannot be empty.");
    }

    #[test]
    fn test_transaction_new_invalid_date_format() {
        let transaction = Transaction::new(
            "15-01-2025".to_string(),
            "Bob".to_string(),
            -200,
            None,
        );
        assert!(transaction.is_err());
        assert_eq!(transaction.unwrap_err(), "Date must be in YYYY-MM-DD format.");

        let transaction_malformed_date = Transaction::new(
            "2025/01/15".to_string(),
            "Bob".to_string(),
            -200,
            None,
        );
        assert!(transaction_malformed_date.is_err());
        assert_eq!(transaction_malformed_date.unwrap_err(), "Date must be in YYYY-MM-DD format.");
    }

    #[test]
    fn test_transaction_new_with_defaults_no_date() {
        let transaction = Transaction::new_with_defaults(
            None,
            "Charlie".to_string(),
            -1500,
            Some("Dinner".to_string()),
        );
        assert!(transaction.is_ok());
        let tx = transaction.unwrap();
        // Check if the date is today's date in YYYY-MM-DD format
        let today = Local::now().format("%Y-%m-%d").to_string();
        assert_eq!(tx.date, today);
        assert_eq!(tx.person, "Charlie");
        assert_eq!(tx.amount, -1500);
        assert_eq!(tx.note, Some("Dinner".to_string()));
    }

    #[test]
    fn test_transaction_new_with_defaults_with_date() {
        let transaction = Transaction::new_with_defaults(
            Some("2024-12-25".to_string()),
            "David".to_string(),
            2500,
            None,
        );
        assert!(transaction.is_ok());
        let tx = transaction.unwrap();
        assert_eq!(tx.date, "2024-12-25");
        assert_eq!(tx.person, "David");
        assert_eq!(tx.amount, 2500);
        assert_eq!(tx.note, None);
    }

    #[test]
    fn test_balance_struct() {
        let balance = Balance {
            person: "Eve".to_string(),
            total_amount: 5000,
        };
        assert_eq!(balance.person, "Eve");
        assert_eq!(balance.total_amount, 5000);
    }
}
